
language: R

r:
  - oldrel
  - release
  - devel

cache: packages

warnings_are_errors: true

os:
  - linux
  - osx

matrix:
  exclude:
    -
      os: osx
      r: oldrel
    -
      os: osx
      r: devel

after_success:
  - if [[ "${TRAVIS_OS_NAME}" = "linux" && "${TRAVIS_R_VERSION_STRING}" = "release" ]]; then Rscript -e 'ls(all.names = T);getwd();sessionInfo()'; fi

before_deploy:
  # so no overwrite of linux build
  - if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then rm -f *.tar.gz; fi
