
language: R

r:
  - oldrel
  - release

cache: packages

warnings_are_errors: true

os:
  - linux

after_success:
  - if [[ "${TRAVIS_OS_NAME}" = "linux" && "${TRAVIS_R_VERSION_STRING}" = "release" ]]; then Rscript -e 'getwd();list.files()'; fi
  - if [[ "${TRAVIS_OS_NAME}" = "linux" && "${TRAVIS_R_VERSION_STRING}" = "release" ]]; then Rscript -e 'if(!requireNamespace("RCurl", quietly = TRUE)) install.packages("RCurl")'; fi
  # send the package to winbuilder
  - if [[ "${TRAVIS_OS_NAME}" = "linux" && "${TRAVIS_R_VERSION_STRING}" = "release" ]]; then Rscript -e 'built_path <- list.files(pattern = "testTravis_[0-9.]+.tar.gz", full.names = T);if(length(built_path)>0){;built_path <- normalizePath(max(built_path));links <- paste0("ftp://win-builder.r-project.org/", c("R-devel", "R-release", "R-oldrelease"), "/", basename(built_path));fup <- function(url) {try(RCurl::ftpUpload(what = built_path, to = url), silent = TRUE)};lapply(links, fup)}'; fi

