language: R
r:
  - oldrel
  - release
  - devel
cache: packages
warnings_are_errors: true
os:
  - linux
  - osx
matrix:
  exclude:
    -
      os: osx
      r: oldrel
    -
      os: osx
      r: devel
after_success:
  - Rscript -e 'ls()'
before_deploy:
  # so no overwrite of linux build
  - if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then rm -f *.tar.gz; fi
