
language: R

r:
  - oldrel
  - release

cache: packages

warnings_are_errors: true

os:
  - linux

after_success:
  - if [[ "${TRAVIS_OS_NAME}" = "linux" && "${TRAVIS_R_VERSION_STRING}" = "release" ]]; then Rscript -e 'getwd();list.files()'; fi
  - if [[ "${TRAVIS_OS_NAME}" = "linux" && "${TRAVIS_R_VERSION_STRING}" = "release" ]]; then Rscript -e 'if(!requireNamespace("RCurl", quietly = TRUE)) install.packages("RCurl")'; fi
  - if [[ "${TRAVIS_OS_NAME}" = "linux" && "${TRAVIS_R_VERSION_STRING}" = "release" ]]; then Rscript -e 'if(!requireNamespace("pkgbuild", quietly = TRUE)) install.packages("pkgbuild")'; fi

